<div class="marker photo_marker" data-info="first" style="top: 300px; left: 400px;">
  <div class="preview">
    Текст для превью Текст для превью
  </div>
  <i class="fa fa-camera"></i>
</div>

<div class="block_container photo_container">

  <div class="control">
    <div class="elem back">
      <i class="fa fa-chevron-left"></i>
    </div>
    <div class="elem close">
      <i class="fa fa-times"></i>
    </div>
  </div>

  <div class="cont first">
    <div class="album_info">
      <div class="name">фотоальбома first - до 70 символов</div>
      <div class="amount">Изображение <span class="cur">3</span> из <span class="len">9</span></div>
    </div>
    <div class="photos">

      <div class="photo">
        <div class="im_cont">
          <img src="/img/photo1.jpg">
        </div>
        <div class="descr">
          <div class="txt">
          txt
          </div>
        </div>
      </div>

    </div>

  </div>
</div>