<div class="marker video_marker" data-info="first" style="top: 300px; left: 500px;">
  <div class="preview">
    Текст для превью Текст для превью
  </div>
  <i class="fa fa-film"></i>
</div>

<div class="block_container video_container"> <!--active-->
  <div class="close">
    <i class="fa fa-times"></i>
  </div>
  <div class="cont first"> <!--active-->
    <div class="album_info">
      <div class="name">Видео first - до 70 символов</div>
      <div class="amount">Изображение <span class="cur">3</span> из <span class="len">9</span></div>
    </div>

    <div class="videos">

      <div class="video"><!--active-->
        <div class="vid_cont first">
          <div class="prev">
            <i class="fa fa-angle-left"></i>
          </div>
          <div class="ifram_cont" data-src="https://www.youtube.com/embed/LXEOVRH7cSU">
            отут видео
          </div>
          <div class="next">
            <i class="fa fa-angle-right"></i>
          </div>
        </div>
        <div style="clear:both"></div>
        <div class="descr">
          <div class="heading">
            <h2>Heading of the</h2>
          </div>
          <div class="txt">
            text of the video
          </div>
        </div>
      </div>
    </div>
  </div>
</div>