<div id="menu-spacer"></div>
<div class="personal_data">
	<div class="cover_container">
		<div class="wallpaper">
			<img class="landscape" src="img/landscape.jpg">
		</div>
		<div class="cover">
			<div class="avatar">
				<img src="img/avatar.jpg">
				<div class="partner">
					<a href="#">parnter</a>
				</div>
			</div>
			<div class="name_status">
				<h2>John Doe</h2>
				<div class="status">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua.
				</div>
			</div>
		</div>
	</div>
	<div class="toolkit">
		<div class="social">
			asd
		</div>
	</div>
</div>