<div id="menu-spacer"></div>
<div class="personal_data">
	<div class="cover_container">
		<div class="wallpaper">
			<img class="landscape" src="/img/landscape.jpg">
		</div>
		<div class="cover">
			<div class="avatar">
				<img src="/img/avatar.jpg">
				<div class="partner">
					<a href="#">parnter</a>
				</div>
			</div>
			<div class="name_status">
				<h2>John Doe</h2>
				<div class="status">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua.
				</div>
			</div>
		</div>
	</div>
	<div class="toolkit">
		<div class="soc_cont_cabinet">
	        <div class="social g-plus">
	          <a href="#">
	            <i class="fa fa-google-plus"></i>
	          </a>
	        </div>
	        <div class="social facebook">
	          <a href="#">
	            <i class="fa fa-facebook"></i>
	          </a>
	        </div>
	        <div class="social pinterest">
	          <a href="#">
	            <i class="fa fa-pinterest-p"></i>
	          </a>
	        </div>
	        <div class="social twitter">
	          <a href="#">
	            <i class="fa fa-twitter"></i>
	          </a>
	        </div>
	        <div class="social youtube">
	          <a href="#">
	            <i class="fa fa-youtube"></i>
	          </a>
	        </div>
	        <div class="social vine">
	          <a href="#">
	            <i class="fa fa-vine"></i>
	          </a>
	        </div>
	        <div class="social vk">
	          <a href="#">
	            <i class="fa fa-vk"></i>
	          </a>
	        </div>
	        <div class="social share">
	          <a href="#">
	            <i class="fa fa-share-alt"></i>
	          </a>
	      	</div>
		</div>
		<a class="conect write">
			<i class="fa fa-envelope-o"></i> Написать
		</a>
		<a class="conect subscribe">
			<i class="fa fa-rss"></i> Подписаться
		</a>
		<div class="clearfix"></div>
		<div class="toombler">
			<div class="profile elem active">
				<a href="#"><i class="fa fa-eye"></i> Смотреть профиль</a>
			</div>
			<div class="pers_data elem">
				<a href="#"><i class="fa fa-info-circle"></i> Персональная информация</a>
			</div>
		</div>

		<div class="pers_data_block active">
			<div class="info">
				<h3>Персональная информация</h3>
				<table>
					<tr>
						<td>
							Страна
						</td>
						<td>
							<a href="#">США</a>
						</td>
					</tr>
					<tr>
						<td>
							Город
						</td>
						<td>
							<a href="#">Сан-Франциско</a>
						</td>
					</tr>
					<tr>
						<td>
							Опыт
						</td>
						<td>
							<a href="#">5 лет</a>
						</td>
					</tr>
					<tr>
						<td>
							Телефон
						</td>
						<td>
							+38 066 274 55 22
						</td>
					</tr>
					<tr>
						<td>
							Skype
						</td>
						<td>
							<a href="skype:stinkymark1?call">stinkymark1</a>
						</td>
					</tr>
					<tr>
						<td>
							E-mail
						</td>
						<td>
							<a href="mailto:stinkymark1@gmail.com">stinkymark1@gmail.com</a>
						</td>
					</tr>
					<tr>
						<td>
							Личный сайт
						</td>
						<td>
							<a href="http://mywebsite.com/">http://mywebsite.com</a>
						</td>
					</tr>
				</table>
				<h4>О себе:</h4>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</div>
			<div class="social_info">
				<div class="elem">
					<span>Подписчиков</span><br/>
					<a href="#">
						<i class="fa fa-heart"></i> <span class="am">2371</span>
					</a>
				</div>
				<div class="elem">
					<span>Туров</span><br/>
					<a href="#">
						<i class="fa fa-street-view"></i> <span class="am">2371</span>
					</a>
				</div>
				<div class="elem">
					<span>Панорама</span><br/>
					<a href="#">
						<i class="fa fa-picture-o"></i> <span class="am">2371</span>
					</a>
				</div>
			</div>
		</div>

		<div class="portfolio">
			<div class="pano_feed feed_container">
			  <div class="items_container">

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			          </p> 
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			          </p> 
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты. 
			          </p>
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			  </div>

			  <div class="pano_container items_container">

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			          </p>
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>


			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			          </p>
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
			          </p>
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			  </div>

			  <div class="pano_container items_container">

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских
			          </p> 
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских 
			          </p>
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских 
			          </p>
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>

			    <div class="pano_item item">
			      <div class="preview">
			        <img src="/img/livadia.jpg">              
			      </div>
			      <div class="info">
			        <div class="description">
			          <h4>
			            Ливадийский дворец
			          </h4>
			          <p>
			            Ливади́йский дворе́ц — бывшая южная резиденция российских 
			          </p>
			        </div>
			        <div class="social">
			          <a href="#">
			            <i class="fa fa-heart"></i> 2756
			          </a>
			          <a href="">
			            <i class="fa fa-clock-o"></i> 2 ч.
			          </a>
			          <a href="">
			            <i class="fa fa-picture-o"></i> 12
			          </a>
			        </div>
			      </div>
			      <div class="clearfix"></div>
			      <div class="author">
			        <div class="avatar">
			          <img src="/img/avatar.jpg">
			        </div>
			        <div class="name">
			          <sub>Автор</sub><br>
			          <a href="#">
			            Sergio_Armyani
			          </a>
			        </div>
			        <div class="tags">
			          <a href="#">Украина</a>
			          <a href="#">Дворец</a>
			          <a href="#">Крым</a>
			          <a href="#">Ливадия</a>
			          <a href="#">Ялта</a>
			          <a href="#">красота</a>
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
		</div>
	</div>
</div>
<div class="spacer"></div>