<div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="body-plain__title">
            <h1 class="text-center">{ЛОГО}</h1>
          </div>
        </div> 
      </div> <!-- / .row -->
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-sm-offset-3 col-md-offset-3 col-lg-offset-4">
          <div class="body-plain__form text-center">
            <p class="lead text-primary">Ошибка <?=$error?></p>
            <p><?=$message?></p>
            <p>
              Go to our <a href="#">homepage</a> or go back to the <a href="#">previous page</a>.
            </p>
            <hr />
			<p style="color:#C7C7C7">
			<?=$this->router->getControllerName();?>/<?=$this->router->getActionName();?></p>
          </div>

          <!-- Footer -->
          <div class="body-plain__footer">
            Copyright 2015 <a href="//placeview.in/">Placeview.in</a>. All Rights Reserved.
          </div>
        </div>
      </div> <!-- / .row -->
    </div> <!-- / .container -->