
<div class="container">
    <div class="panel panel-default center-block" style="width:500px; margin-top:150px; padding:50px;">
        <div class="panel-body text-center">
        <h3 class="text-center">Ошибка <?=$error?></h3>
        <p><?=$message?></p>
        <p><?=$this->router->getControllerName();?></p>
        <p><?=$this->router->getActionName();?></p>
		</div>
	</div>
	<p class="text-center" style="color:#C7C7C7">Developed by Undiabler</p>
</div>
