<div id="menu-spacer"></div>

<div id="feed_container"></div>

<div class="pano_feed feed_container">

<?php 
	$i = 0;
	foreach ($tours as $tour) {
		if ($i%3==0) {
			if ($i>0) echo('</div>');
			echo('<div class="pano_container items_container">');
		}
		$this->partial('widgets/feed_elem',[
			'img'=>'http://img.placeview.in/preview/'.$tour['id'],
			'name'=>$tour['name'],
			'description'=>$tour['description'],
			'avatar'=>'http://img.placeview.in/avatars/ava'.$tour['creator_id'].'.jpg',
			'author_name'=>'noname',
			]);
		$i++;
	} 
	echo('</div>');
?>
  
  <div class="spacer"></div>
</div>


<?php $this->partial("widgets/hover_menu"); ?>
<?php $this->partial("widgets/me"); ?>
<?php $this->partial("widgets/advert"); ?>
<?php $this->partial("widgets/social"); ?>