<div id="menu-spacer"></div>

<div id="feed_container"></div>

<div class="pano_feed feed_container">

<?php
	$i = 0;
	foreach ($tours_array as $tours) {
		echo('<div class="pano_container items_container">');

		foreach ($tours as $tour) {
			$this->partial('widgets/feed_elem',[
				'url'=>'/'.$this->config->lang.'/place/'.$tour['url'],
				'img'=>'http://img.placeview.in/preview/'.$tour['id'],
				'name'=>$tour['name'],
				'description'=>$tour['description'],
				'avatar'=>'http://img.placeview.in/avatars/ava'.$tour['creator_id'].'.jpg',
				'author_name'=>'noname',
				]);
		}

		echo('</div>');
	}
?>

  <div class="spacer"></div>
</div>


<?php $this->partial("widgets/hover_menu"); ?>
<?php $this->partial("widgets/me"); ?>
<?php $this->partial("widgets/advert"); ?>
<?php $this->partial("widgets/social"); ?>