<div id="menu-spacer"></div>

<div class="pano_feed feed_container">
  <div class="pano_container items_container">

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
          </p> 
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
          </p> 
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты. 
          </p>
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

  </div>

  <div class="pano_container items_container">

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
          </p>
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>


    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
          </p>
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
            Ливади́йский дворе́ц — бывшая южная резиденция российских императоров, расположенная на берегу Чёрного моря в посёлке Ливадия в Ялтинском регионе Крыма в 3 км от Ялты.
          </p>
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

  </div>

  <div class="pano_container items_container">

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских
          </p> 
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских 
          </p>
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских 
          </p>
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>

    <div class="pano_item item">
      <div class="preview">
        <img src="img/livadia.jpg">              
      </div>
      <div class="info">
        <div class="description">
          <h4>
            Ливадийский дворец
          </h4>
          <p>
            Ливади́йский дворе́ц — бывшая южная резиденция российских 
          </p>
        </div>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="">
            <i class="fa fa-clock-o"></i> 2 ч.
          </a>
          <a href="">
            <i class="fa fa-picture-o"></i> 12
          </a>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="img/avatar.jpg">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            Sergio_Armyani
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>
  </div>
  <div class="spacer"></div>
</div>


<?php $this->partial("widgets/hover_menu"); ?>
<?php $this->partial("widgets/me"); ?>
<?php $this->partial("widgets/advert"); ?>
<?php $this->partial("widgets/social"); ?>