<?php
$this->assets->addJs("realworld.50000.js");
$this->assets->addJs("js/map.min.js");
$this->assets->addCss("css/map.css");
?>

 <div id="menu-spacer">
    </div>
    <div class="map_container">

<div id="progress">
	<div id="progress-bar">
	</div>
</div>
<div id='map' class="uk-vertical-align uk-text-center"  style="height:100%;"></div>

</div>
  
<?php $this->partial("widgets/hover_menu"); ?>
<?php $this->partial("widgets/me"); ?>
<?php $this->partial("widgets/advert"); ?>
<?php $this->partial("widgets/social"); ?>