<?php
$this->assets->addJs("realworld.50000.js");
$this->assets->addJs("js/map.min.js");
$this->assets->addCss("css/map.css");
?>

 <div id="menu-spacer">
    </div>
    <div class="map_container">

<div id="progress">
	<div id="progress-bar">
	</div>
</div>
<div id='map' class="uk-vertical-align uk-text-center"  style="height:100%;"></div>

</div>
    <div class="menu_container">
      <div class="hover_menu minified">
        <button type="button" class="hide_show">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="filters">
          <a href="#">
            Все
          </a>
          <a href="#" class="active">
            Новые
          </a>
          <a href="#">
            Популярные
          </a>
          <a href="#" class="checkbox_cont">
            <input type="checkbox" />
            Только профи
          </a>
        </span>
        <div class="menu_body">
          <table>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-bars"></i>
              </td>
              <td class="group_name">
                Все рубрики
              </td>
              <td class="tags">
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="me_container">
      <div class="me">
        <i class="fa fa-crosshairs"></i>
      </div>      
    </div>
    <div class="advert_container">
      <div>
        <a class="grey small_padding" href="#" class="list-group-item-heading"><i class="fa fa-info-circle"></i> Инфо</a>
        <a class="grey small_padding" href="#"><i class="fa fa-camera"></i> Заказать виртуальный тур</a>
      </div>
    </div>
    <div class="socials_container">
      <div>
        <div class="social g-plus">
          <a href="#">
            <i class="fa fa-google-plus"></i>
          </a>
        </div>
        <div class="social facebook">
          <a href="#">
            <i class="fa fa-facebook"></i>
          </a>
        </div>
        <div class="social pinterest">
          <a href="#">
            <i class="fa fa-pinterest-p"></i>
          </a>
        </div>
        <div class="social twitter">
          <a href="#">
            <i class="fa fa-twitter"></i>
          </a>
        </div>
        <div class="social youtube">
          <a href="#">
            <i class="fa fa-youtube"></i>
          </a>
        </div>
        <div class="social vine">
          <a href="#">
            <i class="fa fa-vine"></i>
          </a>
        </div>
        <div class="social vk">
          <a href="#">
            <i class="fa fa-vk"></i>
          </a>
        </div>
        <div class="social share">
          <a href="#">
            <i class="fa fa-share-alt"></i>
          </a>
        </div>
      </div>
    </div>