<div id="menu-spacer"></div>

<div class="photographes_feed feed_container">

  <div class="photographer_container items_container">
    <div class="item"> 
      <div class="preview">
         <img src="img/preview.jpg"> 
      </div>
      <div class="avatar">
        <img src="img/avatar.jpg">
      </div>
      <div class="partner">
        <a href="#">
          parnter
        </a>
      </div>
      <div class="info">
        <a class="name" href="#">Sergio_Armyani</a><br />
        <a class="location" href="#">Украина</a> <a class="location" href="#">Днепропетровск</a>
        <p>
          О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла 
        </p>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-eye"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-street-view"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-picture-o"></i> 2756
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="photographer_container items_container">
    <div class="item"> 
      <div class="preview">
         <img src="img/preview.jpg"> 
      </div>
      <div class="avatar">
        <img src="img/avatar.jpg">
      </div>
      <div class="partner">
        <a href="#">
          parnter
        </a>
      </div>
      <div class="info">
        <a class="name" href="#">Sergio_Armyani</a><br />
        <a class="location" href="#">Украина</a> <a class="location" href="#">Днепропетровск</a>
        <p>
          О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла 
        </p>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-eye"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-street-view"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-picture-o"></i> 2756
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="photographer_container items_container">
    <div class="item"> 
      <div class="preview">
         <img src="img/preview.jpg"> 
      </div>
      <div class="avatar">
        <img src="img/avatar.jpg">
      </div>
      <div class="partner">
        <a href="#">
          parnter
        </a>
      </div>
      <div class="info">
        <a class="name" href="#">Sergio_Armyani</a><br />
        <a class="location" href="#">Украина</a> <a class="location" href="#">Днепропетровск</a>
        <p>
          О себе бла-бла-бла О себе бла-бла-бла бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла 
        </p>
        <div class="social">
          <a href="#">
            <i class="fa fa-heart"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-eye"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-street-view"></i> 2756
          </a>
          <a href="#">
            <i class="fa fa-picture-o"></i> 2756
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="spacer"></div>
</div>