<div id="menu-spacer"></div>

<div class="photographes_feed feed_container">

  <div class="photographer_container items_container">
    <div class="item"> 
      <div class="preview">
         <img src="/img/preview.jpg"> 
      </div>
      <div class="avatar">
        <img src="/img/avatar.jpg">
      </div>
      <div class="partner">
        <a href="#">
          parnter
        </a>
      </div>
      <div class="info">
        <div class="name_location">
          <a class="name" href="#">Sergio_Armyani</a><br />
          <a class="location" href="#">Украина</a> <a class="location" href="#">Днепропетровск</a>
        </div>
        <p>
          О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла 
        </p>
        <div class="social">
          <div class="elem">
            <i class="fa fa-heart"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-eye"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-street-view"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-picture-o"></i> 2756
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="photographer_container items_container">
    <div class="item"> 
      <div class="preview">
         <img src="/img/preview.jpg"> 
      </div>
      <div class="avatar">
        <img src="/img/avatar.jpg">
      </div>
      <div class="partner">
        <a href="#">
          parnter
        </a>
      </div>
      <div class="info">
        <div class="name_location">
          <a class="name" href="#">Sergio_Armyani</a><br />
          <a class="location" href="#">Украина</a> <a class="location" href="#">Днепропетровск</a>
        </div>

        <p>
          О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла 
        </p>
        <div class="social">
          <div class="elem">
            <i class="fa fa-heart"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-eye"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-street-view"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-picture-o"></i> 2756
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="photographer_container items_container">
    <div class="item"> 
      <div class="preview">
         <img src="/img/preview.jpg"> 
      </div>
      <div class="avatar">
        <img src="/img/avatar.jpg">
      </div>
      <div class="partner">
        <a href="#">
          parnter
        </a>
      </div>
      <div class="info">
        <div class="name_location">
          <a class="name" href="#">Sergio_Armyani</a><br />
          <a class="location" href="#">Украина</a> <a class="location" href="#">Днепропетровск</a>
        </div>
        <p>
          О себе бла-бла-бла О себе бла-бла-бла бла О себе бла-бла-бла О себе бла-бла-бла О себе бла-бла-бла 
        </p>
        <div class="social">
          <div class="elem">
            <i class="fa fa-heart"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-eye"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-street-view"></i> 2756
          </div>
          <div class="elem">
            <i class="fa fa-picture-o"></i> 2756
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="spacer"></div>
</div>

<?php $this->partial("widgets/hover_menu"); ?>
<?php $this->partial("widgets/me"); ?>
<?php $this->partial("widgets/advert"); ?>
<?php $this->partial("widgets/social"); ?>