<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title></title>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300&subset=latin,cyrillic,cyrillic-ext' rel='stylesheet' type='text/css'>
  <link href="/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/css/player/player.css" />
  <!-- подключаем панораму -->
  <script type="text/javascript" src="http://features.placeview.in:9999/js/libs/modernizr.js"></script>
  <script type="text/javascript" src="http://features.placeview.in:9999/js/init.min.js"></script>
</head>
<body>
  <div id="player">

    <div class="marker" style="top: 300px; left: 300px;">
      <i class="fa fa-info"></i>
    </div>
    <div class="marker" style="top: 300px; left: 400px;">
      <i class="fa fa-camera"></i>
    </div>
    <div class="marker" style="top: 300px; left: 500px;">
      <i class="fa fa-film"></i>
    </div>

    <div class="info_block">
    </div>
    <div id="pano">
      <div id="container" style='position:fixed;z-index:0;width:100%;height:100%; top: 0px;left: 0px;'></div>
      <script type="text/javascript">
          PVLoader({tid:500,pid:1404,manualLoad:false});
      </script>
    </div>

    <div id="top_menu">
      <div class="tour_name">
        <span>Гостиница абри</span>
      </div>
      <div class="pano_name">
        Гостиница абри не более 60ти символов
      </div>
    </div>

    <div id="pano_list">
      <div id="show_hide_panos" class="control">
        <div class="show">
          Панорамы <i class="fa fa-angle-down"></i>
        </div>
        <div class="hide">
          Свернуть <i class="fa fa-angle-up"></i>
        </div>

        <div class="slides">

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1 <br />asdasd
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

          <div class="slide">
            <div class="pano">
              <img src="/img/preview.jpg">
            </div>
            <div class="name">
              name1
            </div>
          </div>

      </div>
    </div>


  </div>
  <div id="logo">
    <a href="#">
      <img src="/img/logo.jpg">
    </a>
  </div>
  <div id="multimenu" class="default">
    <div id="default">
      <div class="icons_minimals">
        <div class="icon show_on_map">
          <i class="fa fa-map-marker"></i>
        </div>
        <div class="icon contact">
          <i class="fa fa-phone"></i>
        </div>
        <div class="icon qr-code">
          <i class="fa fa-qrcode"></i>
        </div>
        <div class="icon share">
          <i class="fa fa-share-alt"></i>
        </div>
        <div class="icon meeting">
          <i class="fa fa-flag"></i>
        </div>
        <div class="icon warning">
          <i class="fa fa-exclamation-triangle"></i>
        </div>
        <div class="lang">
          <div class="cur">
            RU
          </div>
          <div class="list">
            <div>
              RU
            </div>
            <div>
              ENG
            </div>
            <div>
              DE
            </div>
          </div>
        </div>
      </div>
      <div class="info">
        <i class="fa fa-info-circle"></i>
      </div>
    </div>
    <div id="more_info" class="panel">
      <div class="description">
        Premier Hotel Abri открыл свои двери гостям и жителям Днепропетровска. Отель расположен в непосредственной близости от культурно-исторического центра города.
      </div>
      <div class="menu">
        <a href="#" class="elem show_on_map">
          <i class="fa fa-map-marker"></i> Показать на карте
        </a>
        <a href="#" class="elem contact">
          <i class="fa fa-phone"></i> Контакты
        </a>
        <a href="#" class="elem qr-code">
          <i class="fa fa-qrcode"></i> QR код
        </a>
        <a href="#" class="elem share">
          <i class="fa fa-share-alt"></i> Поделиться
        </a>
        <a href="#" class="elem meeting">
          <i class="fa fa-flag"></i> Назначить встречу
        </a>
        <a href="#" class="elem warning">
          <i class="fa fa-exclamation-triangle"></i> Сообщить о ошибке
        </a>
        <div class="lang">
          <a href="#" class="active">RU</a>
          <a href="#">EN</a>
        </div>
      </div>
      <div class="back_button">
        Свернуть <i class="fa fa-angle-right"></i>
      </div>
    </div>
    <div id="contact" class="panel">
      <div class="control">
        <i class="fa fa-phone active"></i>
        <i class="fa fa-times"></i>
      </div>
      <div class="contact-date">
        <i class="fa fa-phone"></i> (0562) 31 85 36
      </div>
      <div class="contact-date">
        <i class="fa fa-phone"></i> (056) 731 87 88
      </div>
      <div class="contact-date">
        <i class="fa fa-at"></i> hotel@hotel
      </div>
      <div class="contact-date">
        <a href="#">
          <i class="fa fa-globe"></i> www.abri-hotel.com
        </a>
      </div>
      <div class="contact-date">
        <a href="#">
          <i class="fa fa-skype"></i> abri-hotel
        </a>
      </div>
      <div class="social links-4">
        <a href="#" class="bg_fb_color"><i class="fa fa-facebook"></i></a>
        <a href="#" class="bg_g_color"><i class="fa fa-google-plus"></i></a>
        <a href="#" class="bg_tw_color"><i class="fa fa-twitter"></i></a>
        <a href="#" class="bg_vk_color"><i class="fa fa-vk"></i></a>
      </div>
      <div class="back_button">
        Свернуть <i class="fa fa-angle-right"></i>
      </div>
    </div>
    <div id="share" class="panel">
      <div class="control">
        <i class="fa fa-share-alt active"></i>
        <i class="fa fa-times"></i>
      </div>
      <div class="share_friends">
        <div class="decr">
          Поделится с друзьями ссылкой
        </div>
        <div class="social">
          <a href="#" class="bg_g_color"><i class="fa fa-google-plus"></i></a>
          <a href="#" class="bg_fb_color"><i class="fa fa-facebook"></i></a>
          <a href="#" class="bg_pin_color"> <i class="fa fa-pinterest-p"></i></a>
          <a href="#" class="bg_tw_color"><i class="fa fa-twitter"></i></a>
          <a href="#" class="bg_vk_color"><i class="fa fa-vk"></i></a>
        </div>
        <div style="clear: both;"></div>
        <div class="html-code">
          <i class="fa fa-code square"></i> HTML-code
          <div class="code">
            &lt;iframe width="800" height="600" frameborder="0" src="http://placeview.in/pano/1392"&gt

            &lt;/iframe&gt
          </div>
        </div>
        <div class="check_size">
          <div class="title">
            Размер фрейма панорамы
          </div>
          <div class="select">
            <div class="title">
              <div class="txt">800 x 600</div>
              <div class="down">
                <i class="fa fa-angle-down"></i>
              </div>
            </div>
            <div style="clear: both;"></div>
            <div class="options">
              <div class="option">
                640 x 480
              </div>
              <div class="option">
                800 x 600
              </div>
              <div class="option">
                1024 x 768
              </div>
              <div class="option">
                1280 x 720
              </div>
              <div class="option">
                1366 x 768
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="back_button">
        Свернуть <i class="fa fa-angle-right"></i>
      </div>
    </div>
    <div id="warning" class="panel">
      <div class="control">
        <i class="fa fa-exclamation-triangle active"></i>
        <i class="fa fa-times"></i>
      </div>
      <div class="descr">
        Пожалуйста, выберите о чем Вы хотите сообщить
      </div>
      <div class="choose">
        <a href="#">
          <input type="radio" name="theme_warning" value="Сообщить о ошибке"> Сообщить о ошибке
        </a>
        <a href="#">
          <input type="radio" name="theme_warning" value="Отправить жалобу"> Отправить жалобу
        </a>
        <a href="#">
          <input type="radio" name="theme_warning" value="Отметить как спам"> Отметить как спам
        </a>
      </div>
      <textarea></textarea>
      <button>Отправить сообщение</button>
      <div class="back_button">
        Свернуть <i class="fa fa-angle-right"></i>
      </div>
    </div>
    <div id="qr-code" class="panel">
      <div class="control">
        <i class="fa fa-qrcode active"></i>
        <i class="fa fa-times"></i>
      </div>
      <img src="/img/qr-code.png">
      <div class="choose">
        <a href="#" class="var active">GPS</a>
        <a href="#" class="var">Link</a>
      </div>
      <div class="back_button">
        Свернуть <i class="fa fa-angle-right"></i>
      </div>
    </div>
    <div id="meeting" class="panel">
      <div class="control">
        <i class="fa fa-flag active"></i>
        <i class="fa fa-times"></i>
      </div>
      <input type="text" placeholder="Введите заголовок встречи">
      <textarea placeholder="Введите описание встречи"></textarea>
      <div class="send_mesage">
        <div class="txt">
          Отпрваить приглашения на встречу личным сообщением через
        </div>
        <div class="social links-4">
          <a href="#" class="bg_fb_color"><i class="fa fa-facebook"></i></a>
          <a href="#" class="bg_g_color"><i class="fa fa-google-plus"></i></a>
          <a href="#" class="bg_tw_color"><i class="fa fa-twitter"></i></a>
          <a href="#" class="bg_vk_color"><i class="fa fa-vk"></i></a>
        </div>
        <div class="txt">
          или
        </div>      
        <div class="meeting-link">
          <a href="#">
            Копировать ссылку-приглашение
          </a>
        </div>
        <div class="txt">
          Эту информацию увидят те пользователи, у которых есть ссылка-приглашение
        </div>
      </div>
      <div class="back_button">
        Свернуть <i class="fa fa-angle-right"></i>
      </div>
    </div>
    <div id="show_on_map" class="panel">
      <div class="control">
        <i class="fa fa-map-marker active"></i>
        <i class="fa fa-times"></i>
      </div>
      <div class="map_container">
        <div style="background:green;overflow:hidden;width:300px;height:300px;">
        
        </div>        
      </div>
      <div class="addres">
        ул. Рогалева 16 <br />
        г. Днепропетровск, Украина
        <a href="#" class="coordinates">
          58.34434, 14.23232
        </a>
      </div>
      <div class="back_button">
        Свернуть <i class="fa fa-angle-right"></i>
      </div>
    </div>
  </div>
  <div id="close_all">
    <span>
      <i class="fa fa-angle-left"></i> Свернуть все <i class="fa fa-angle-right"></i>
    </span>
  </div>

  <script src="/js/player/player.js"></script>
</body>
</html>