    <!-- PAGE CONTENT
    ============================== -->
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="body-plain__title">
            <h1 class="text-center"><?=$t->_('sign_register');?></h1>
          </div>
        </div> 
      </div> <!-- / .row -->
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-sm-offset-3 col-md-offset-3 col-lg-offset-4">
          <div class="body-plain__form">

            <!-- Sign Up form -->
            <form role="form">
              <div class="form-group">
                <label for="sign-up__email" class="sr-only"><?=$t->_('sign_email');?></label>
                <input type="email" class="form-control" id="sign-up__email" placeholder="<?=$t->_('sign_email');?>">
              </div>
              <div class="checkbox">
                <label>
                  Pressing this button you agree to the <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a>
                </label>
              </div>
              <button type="submit" class="btn btn-primary btn-block btn-lg">Create Account</button>
            </form>

            <!-- Sign In link -->
            <hr />
            <p><?=$t->_('sign_already');?> <?=$this->extra->url([['for'=>'index_act','action'=>'sign_in'],$t->_('sign_into')])?></p>
          </div> <!-- / .body-plain__form -->

          <!-- Footer -->
          <div class="body-plain__footer">
            Copyright 2015 <a href="http://placeview.in/">Placeview.in</a>. All Rights Reserved.
          </div>
        </div>
      </div> <!-- / .row -->
    </div> <!-- / .container -->