    <!-- PAGE CONTENT
    ============================== -->
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="body-plain__title">
            <h1 class="text-center"><?=$t->_('sign');?></h1>
          </div>
        </div> 
      </div> <!-- / .row -->
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-sm-offset-3 col-md-offset-3 col-lg-offset-4">
          <div class="body-plain__form">

            <!-- Sign In form -->
            <form role="form">
              <label for="sign-in__email" class="sr-only"><?=$t->_('sign_email');?></label>
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <input type="email" class="form-control" id="sign-in__email" placeholder="<?=$t->_('sign_email');?>">
              </div>
              <br>
              <label for="sign-in__password" class="sr-only"><?=$t->_('sign_pass');?></label>
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                <input type="password" class="form-control" id="sign-in__password" placeholder="<?=$t->_('sign_pass');?>">
              </div>
              <br>
              <!-- <div class="checkbox"> 
                <label>
                  <input type="checkbox"> <?=$t->_('sign_remember');?>
                </label>
              </div>
              -->
              <button type="submit" class="btn btn-primary btn-block btn-lg"><?=$t->_('sign_submit');?></button>
            </form>

            <!-- Sign Up link -->
            <hr />
            <p><?=$t->_('sign_notreg');?> <a href="sign-up.html"><?=$t->_('sign_create');?></a></p>

            <!-- Lost password form -->
            <p>
              Lost your password? <a href="#lost-password__form" data-toggle="collapse" aria-expanded="false" aria-controls="lost-password__form">Click here to recover.</a>
            </p>
            <div class="collapse" id="lost-password__form">
              <p class="text-muted">
                Enter your email address below and we will send you a link to reset your password.
              </p>
              <form class="form-inline" role="form">
                <div class="form-group">
                  <label class="sr-only" for="lost-password__email">Email address</label>
                  <input type="email" class="form-control" id="lost-password__email" placeholder="Enter email">
                </div>
                <button type="submit" class="btn btn-info">Send</button>
              </form>
            </div> <!-- lost-password__form -->
          </div> <!-- / .body-plain__form -->

          <!-- Footer -->
          <div class="body-plain__footer">
            Copyright 2015 <a href="http://placeview.in/">Placeview.in</a>. All Rights Reserved.
          </div>
        </div>
      </div> <!-- / .row -->
    </div> <!-- / .container -->
