<li class="<?=$name=='camps'?'active':''?>"> 	<?=$this->tag->linkTo('camps','Кампании')?> </li>
<li class="<?=$name=='clients'?'active':''?>"> 	<?=$this->tag->linkTo('clients','Клиенты')?> </li>
<!-- <li class="<?=$name=='svm'?'active':''?>">      <?=$this->tag->linkTo('svm','Ротация')?></li> -->
<li class="<?=$name=='cpanel'?'active':''?>">   <?=$this->tag->linkTo('cpanel','Общая статистика')?></li>
<li class="dropdown">
    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Дополнительно <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="javascript:void(0)">Логи</a></li>
        <li><a href="javascript:void(0)">Удаленное управление</a></li>
        <li class="divider"></li>
        <li class="dropdown-header">Кампании</li>
        <li><?=$this->tag->linkTo('camps/lo','Ленды/Оферы')?></li>
        <li><?=$this->tag->linkTo('camps/opt','Свойства кампаний')?></li>
        <li class="divider"></li>
        <li class="dropdown-header">Экстра функции</li>
        <li><a href="javascript:void(0)">Обновление</a></li>
        <li><a href="javascript:void(0)">Удаление / отключение</a></li>
    </ul>
</li>