<!DOCTYPE html> 
<html> 
    <head> 
    <meta name="viewport" content="width=device-width, initial-scale=1,minimum-scale=1,maximum-scale=1">
    <link rel="shortcut icon" href="/favicon.ico"></link>
        
        <meta charset="UTF-8">
        <!--[if lte IE 9]>
          <script type="text/javascript">location.href='/site/noie';</script>
        <![endif]-->

        <meta name="keywords" content="" />
        <meta name="description" content="PlaceView.in – это web-платформа для создания (конструирования и администрирования), размещения и продвижения интерактивных виртуальных туров в сети Интернет. Платформа виртуальной реальности PlaceView.in способствует развитию рынка недвижимости, индустрии гостеприимства HoReCa, туризма и культуры, а так же многих других сфер бизнеса, для которых полезен визуальный образ места, как например автосалоны, магазины аксессуаров, развлекательные комплексы и пр." />
        <meta name="language" content="ru" />
        <meta name="autor" content="placeview.in" />
        <meta name="title" content="Конструктор интерактивных витруальныx туров." />
        <meta name="og:title" content="Конструктор интерактивных витруальныx туров." />
        <meta name="og:type" content="website" />
        <meta name="og:url" content="http://placeview.in/" />
        <meta name="og:image" content="http://placeview.in/img/site/LOGO_BETA.png" />

        <link rel="stylesheet" href="/css/uikit.almost-flat.css">

        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

        <script type="text/javascript" src="/js/uikit.js"></script>



        <!-- <link href='/assets/css/map.css' rel='stylesheet' /> -->
         <?php $this->assets->outputCss() ?>


         <link href="/css/styles.css" rel="stylesheet">

    <!-- CSS Plugins -->
    <link href="/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="/css/placeview.css" rel="stylesheet">

        <title>PlaceView — Конструктор интерактивных витруальныx туров.</title> 

    </head> 
    <body class="uk-height-1-1">      

    <!-- PRELOADER
    ============================== -->
    <div class="preloader">
      <img src="img/preloader.gif" alt="Loading..." class="preloader__img">
    </div>

	<?php $this->partial("layouts/header"); ?>
   
	<?php echo $this->getContent() ?>
    
	<?php $this->assets->outputJs() ?>

        <script src="/js/bootstrap/bootstrap.min.js"></script>

    <!-- JS Plugins -->
        <script src="/js/backstretch.min.js"></script>
        <script src="/js/counter.js"></script>
        <script src="/js/scrolltopcontrol.js"></script>
        <script src="/js/wow.min.js"></script>
        <script src="/js/contact.js"></script>

        <!-- JS Custom -->
        <script src="/js/custom.js"></script>
        <script src="/js/custom_hero.js"></script>

        <!-- custom js-->

        <script src="/js/placeview.js"></script>

    </body>
</html>