<div class="pano_item item">
      <a class="preview">
        <img src="<?=$img?>">
      </a>
      <div class="info">
        <div class="description">
          <h4>
            <a href="#">
              <?=$name?>
            </a>
          </h4>
          <p><?=substr($description,0,300)?></p>
        </div>
        <div class="social">
          <span class="elem">
            <i class="fa fa-eye"></i> 2756
          </span>
          <span class="elem">
            <i class="fa fa-heart"></i> 2756
          </span>
          <span class="elem">
            <i class="fa fa-clock-o"></i> 2 ч.
          </span>
          <span class="elem">
            <i class="fa fa-picture-o"></i> 12
          </span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="author">
        <div class="avatar">
          <img src="<?=$avatar?>">
        </div>
        <div class="name">
          <sub>Автор</sub><br/>
          <a href="#">
            <?=$author_name?>
          </a>
        </div>
        <div class="tags">
          <a href="#">Украина</a>
          <a href="#">Дворец</a>
          <a href="#">Крым</a>
          <a href="#">Ливадия</a>
          <a href="#">Ялта</a>
          <a href="#">красота</a>
        </div>
      </div>
    </div>
