 <!-- FIXED NAVBAR
    ============================== -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!-- Toggle button -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- Brand name -->
      <a class="navbar-brand" href="/">
        <img src="img/LOGO_BETA.png">
      </a>
    </div>
    <div class="visible-md visible-lg">
      <form class="navbar-form navbar-left find-form " role="search">
          <div class="form-group">
            <button type="submit" class="btn btn-default">
              <i class="fa fa-search"></i>
            </button>
      <label class="sr-only" for="nav-search-xs">Search</label>
      <input type="search" class="form-control" id="nav-search-xs" placeholder="Поиск">
    </div>
  </form>
    </div>
    <div class="collapse navbar-collapse">
      <!-- Navbar links -->
  <ul class="nav navbar-nav navbar-left">
    <!-- Home -->
    <li >
      <a href="/feed">
        <i class="fa fa-eye"></i> Лента туров
            </a>
            </li>
            <!-- Profile -->
            <li >
        <a href="#">
          <i class="fa fa-magic"></i> Создать
        </a>
            </li>
            <!-- Portfolio -->
            <li>
        <a href="/photographers">
          <i class="fa fa-users"></i> Фотографы
        </a>
            </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
        <!-- Home -->
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        RU <span class="fa fa-angle-down"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li class="active">
          <a href="#">RU</a>
        </li>
        <li>
          <a href="#">EN</a>
        </li>
      </ul>
    </li>
    <!-- Profile -->
    <li >
      <a href="#">
        Войти
      </a>
    </li>
  </ul>


  <!-- Search form (for collapsed menu only) -->
      <form class="navbar-form navbar-left visible-xs visible-sm" role="search">
        <div class="form-group">
          <label class="sr-only" for="nav-search-xs">Search</label>
          <input type="search" class="form-control" id="nav-search-xs" placeholder="Search here...">
        </div>
      </form>
    </div> <!-- / .navbar-collapse -->
  </div> <!-- / .container -->
</div> <!-- / .navbar -->