 <!-- FIXED NAVBAR
    ============================== -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!-- Toggle button -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- Brand name -->
      <a class="navbar-brand" href="/">
        <img src="/img/LOGO_BETA.png">
      </a>
    </div>
    <div class="visible-md visible-lg">
      <form class="navbar-form navbar-left find-form " role="search">
          <div class="form-group">
            <button type="submit" class="btn btn-default">
              <i class="fa fa-search"></i>
            </button>
      <label class="sr-only" for="nav-search-xs"><?=$t->_('search')?></label>
      <input type="search" class="form-control" id="nav-search-xs" placeholder="<?=$t->_('search')?>">
    </div>
  </form>
    </div>
    <div class="collapse navbar-collapse">
      <!-- Navbar links -->
  <ul class="nav navbar-nav navbar-left">
    <!-- Home -->
    <li><?=$this->extra->url([['for'=>'index_act','action'=>'feed'],'<i class="fa fa-eye"></i> '.$t->_('feed')])?></li>
	<li><a href="#"><i class="fa fa-magic"></i> <?=$t->_('create')?></a></li>
	<li><?=$this->extra->url([['for'=>'index_act','action'=>'photographers'],'<i class="fa fa-users"></i> '.$t->_('p_men')])?></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
        <!-- Home -->
    <?php $this->partial("widgets/langs"); ?>
   
    <?php $this->partial("widgets/header/logined"); ?>
  </ul>


  <!-- Search form (for collapsed menu only) -->
      <form class="navbar-form navbar-left visible-xs visible-sm" role="search">
        <div class="form-group">
          <label class="sr-only" for="nav-search-xs">Search</label>
          <input type="search" class="form-control" id="nav-search-xs" placeholder="Search here...">
        </div>
      </form>
    </div> <!-- / .navbar-collapse -->
  </div> <!-- / .container -->
</div> <!-- / .navbar -->