<div class="menu_container">
      <div class="hover_menu minified">
        <button type="button" class="hide_show">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="filters">
          <a href="#">
            Все
          </a>
          <a href="#" class="active">
            Новые
          </a>
          <a href="#">
            Популярные
          </a>
          <a href="#" class="checkbox_cont">
            <input type="checkbox" />
            Только профи
          </a>
        </span>
        <div class="menu_body">
          <table>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-cutlery"></i>
              </td>
              <td class="group_name">
                Поесть
              </td>
              <td class="tags">
                Кафе, ресторан, Бар, Пиццерия, Суши, Чайная, Фастфуд
              </td>
            </tr>
            <tr>
              <td class="pictogramm">
                <i class="fa fa-bars"></i>
              </td>
              <td class="group_name">
                Все рубрики
              </td>
              <td class="tags">
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>