
<?php 

$langs = $this->config->langs;

if (preg_match("/^\/\w{2}\//",$_SERVER['REQUEST_URI'] )) {

$c_lang = $this->config->lang;

?>


    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <?=strtoupper($c_lang)?> <span class="fa fa-angle-down"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
      <?php 
      	foreach ($langs as $lang) {
	if ($lang==$c_lang) continue;
	$new_l=preg_replace('/^\/\w{2}\//',"/$lang/",$_SERVER['REQUEST_URI']);
      ?>
        <li><a href="<?=$new_l?>"><?=strtoupper($lang)?></a></li>
      <?php 
      }
      ?>
      </ul>
    </li>

<?php } ?>