<div class="socials_container">
  <div>
    <div class="social g-plus">
      <a href="#">
        <i class="fa fa-google-plus"></i>
      </a>
    </div>
    <div class="social facebook">
      <a href="#">
        <i class="fa fa-facebook"></i>
      </a>
    </div>
    <div class="social pinterest">
      <a href="#">
        <i class="fa fa-pinterest-p"></i>
      </a>
    </div>
    <div class="social twitter">
      <a href="#">
        <i class="fa fa-twitter"></i>
      </a>
    </div>
    <div class="social youtube">
      <a href="#">
        <i class="fa fa-youtube"></i>
      </a>
    </div>
    <div class="social vine">
      <a href="#">
        <i class="fa fa-vine"></i>
      </a>
    </div>
    <div class="social vk">
      <a href="#">
        <i class="fa fa-vk"></i>
      </a>
    </div>
    <div class="social share">
      <a href="#">
        <i class="fa fa-share-alt"></i>
      </a>
    </div>
  </div>
</div>