<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AIMGOD</title>
    <link rel="stylesheet" href="/static/css/jquery-ui.css"/>
    <link rel="stylesheet" href="/static/css/style.css"/>
</head>
<body>
     <?php echo $this->getContent() ?>
     <!--<script src="js/jquery-1.10.2.min.js"></script>-->
<!--     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>-->
     <script src="/static/js/jquery-1.11.2.min.js"></script>
     <script src="/static/js/jquery-ui.min.js"></script>
     <script src="/static/js/tasks.js"></script>
     <script src="/static/js/datepicker.js"></script>
     <script src="/static/js/dialog.js"></script>
<!--     <script src="static/js/event-form.js"></script>-->
     <script src="/static/js/i18n-jquer-ui.js"></script>
     <script src="/static/js/jquery.mCustomScrollbar.concat.min.js"></script>
     <script src="/static/js/script.js"></script>
</body>
</html>