<?php 


$langs = $this->config->langs->toArray();

$selectbox = [];
foreach ($langs as $key => $value) {
	$selectbox[$value]=$t->_($value);
}


?>

<div id="menu-spacer"></div>
<div class="container">
<div class="row">
	<br>
	<div class="ui__section">
		<h4>Выберите направление перевода</h4>
	<form role="form">
	<div class="form-group">
		
		<div class="row">
			<div class="col-sm-6">
				
			<?=$this->tag->selectStatic(
						    array(
						        "from",
						        $selectbox,
						        'class'=>'form-control'
						    )
						    )?>
			</div>

			<div class="col-sm-6">
				
			<?=$this->tag->selectStatic(
						    array(
						        "to",
						        $selectbox,
						        'class'=>'form-control'
						    )
						    )?>
			</div>
		</div>
	</div>
		<div class="form-group">
			<input type="submit" class="btn btn-sm btn-primary" value="Приступить к переводам" />
		</div>
	</form>
	</div>
</div>
</div>