<!DOCTYPE html> 
<html> 
    <head> 
    <meta name="viewport" content="width=device-width, initial-scale=1,minimum-scale=1,maximum-scale=1">
    <link rel="shortcut icon" href="/favicon.ico"></link>
        
        <meta charset="UTF-8">
        <!--[if lte IE 9]>
          <script type="text/javascript">location.href='/site/noie';</script>
        <![endif]-->

        <meta name="keywords" content="" />
        <meta name="description" content="PlaceView.in – это web-платформа для создания (конструирования и администрирования), размещения и продвижения интерактивных виртуальных туров в сети Интернет. Платформа виртуальной реальности PlaceView.in способствует развитию рынка недвижимости, индустрии гостеприимства HoReCa, туризма и культуры, а так же многих других сфер бизнеса, для которых полезен визуальный образ места, как например автосалоны, магазины аксессуаров, развлекательные комплексы и пр." />
        <meta name="language" content="ru" />
        <meta name="autor" content="placeview.in" />
        <meta name="title" content="Конструктор интерактивных витруальныx туров." />
        <meta name="og:title" content="Конструктор интерактивных витруальныx туров." />
        <meta name="og:type" content="website" />
        <meta name="og:url" content="http://placeview.in/" />
        <meta name="og:image" content="http://placeview.in/img/site/LOGO_BETA.png" />

        <link rel="stylesheet" href="/assets/css/uikit.almost-flat.css">

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script type="text/javascript" src="/assets/js/uikit.js"></script>

        <!-- <link href='/assets/css/map.css' rel='stylesheet' /> -->
         <?php $this->assets->outputCss() ?>


        <title>PlaceView — Конструктор интерактивных витруальныx туров.</title> 

    </head> 
    <body class="uk-height-1-1">      

   <nav class="uk-navbar" style="background-color:#A5A5A5;">

      <ul class="uk-navbar-nav">
        <img src="/img/LOGO_BETA.png"/>
      </ul>


      <div class="uk-navbar-flip">

          <ul class="uk-navbar-nav">
              <li class="uk-hidden-small"><a href="/people">Фотографы</a></li>
              <li class="uk-hidden-small"><a href="/login">Вход</a></li>
          </ul>

      </div>
      <div class="uk-navbar-center">
        <div class="uk-grid">
           <div class="uk-container-center">
              <ul class="uk-navbar-nav uk-navbar-content ">
                  <li class="uk-active"><a href="">Смотреть</a></li>
                  <li class="uk-hidden-small"><a href="">Создать</a></li>
                  <li class="uk-hidden-small"><a href="">Заказать</a></li>
                 
              </ul>
           </div>
        </div>
      </div>                   

    </nav>

        <?php echo $this->getContent() ?>

  

<!-- 
        <script type="text/javascript" language="javascript" src="/js/material/ripples.min.js"></script>
        <script type="text/javascript" language="javascript" src="/js/material/material.min.js"></script>
        <script type="text/javascript" language="javascript" src="/js/material/snackbar.min.js"></script>
 -->


        <?php $this->assets->outputJs() ?>

    </body>
</html>