
     <div class="container">
       
          <div class="panel panel-default center-block" style="width:500px; margin-top:50px; padding:50px;">
          <?php echo $this->flash->output() ?>
            <div class="panel-heading">Заявка на регистрацию нового пользователя <?=$this->tag->linkTo(['login','class'=>'pull-right','Вход'])?></div>
            <div class="panel-body">
             
              <form class="form" method="post">
                <fieldset>
                  <div class="form-group">
                    <?=$this->tag->textField(['username','class'=>'form-control','placeholder'=>'логин'])?>
                  </div>
                  <div class="form-group">
                    <?=$this->tag->textField(['email','class'=>'form-control','placeholder'=>'email'])?>
                  </div>
                  <div class="form-group">
                      <?=$this->tag->passwordField(['userpass','class'=>'form-control','placeholder'=>'пароль'])?>
                  </div>
                  <div class="form-group">
                      <?=$this->tag->passwordField(['userpass2','class'=>'form-control','placeholder'=>'подтвердите пароль'])?>
                  </div>
                  <div class="form-group">
                      <?=$this->tag->textArea(['comment','class'=>'form-control','placeholder'=>'Примечание к вашей заявке (можно оставить пустым)'])?>
                  </div>
                  <div class="form-group">
                      <button type="submit"  class="center-block btn btn-primary">Отправить заявку</button>
                  </div>
                </fieldset>
              </form>
              <p>Обратите внимание на то что заявки на добавление пользователей рассматриваются в ручном режиме. Вы не сможете пользоваться своим аккаунтом до подтверждения вашего запроса.</p>
            
            </div>
     
        </div> 
        <p class="text-center light_c">Developed by Undiabler</p>       
      </div>


