<?php 


	$this->assets
				->addJs("js/jquery.dataTables.js")
				->addJs('js/dataTables.bootstrap.js')
				// ->addJs("http://code.highcharts.com/maps/highmaps.js")
				->addJs("http://code.highcharts.com/highcharts.js")
				->addJs("http://code.highcharts.com/maps/modules/map.js")
				->addJs("http://code.highcharts.com/maps/modules/data.js")
				->addJs("http://code.highcharts.com/mapdata/countries/cn/cn-all.js")
				->addJs("http://code.highcharts.com/mapdata/custom/world.js")
				->addJs("js/map.js")
				->addJs("js/charts.js")
				->addJs('js/filter.js');

 ?>

 <?php echo $this->getContent(); ?>